name: string-conversions
version: "0.4.0.1"
synopsis: Simplifies dealing with different types for strings
description: Provides a simple type class for converting values
  of different string types
  into values of other string types.
license: BSD3
author: Sönke Hahn
maintainer: soenkehahn@gmail.com
category: Data

github: soenkehahn/string-conversions

tested-with: GHC == 8.0.1

dependencies:
  - base == 4.*
  - bytestring >= 0.9
  - text >= 0.11
  - utf8-string >= 0.3

library:
  ghc-options: -Wall
  source-dirs:
    - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - quickcheck-instances
      - deepseq
      - QuickCheck
    build-tools: hspec-discover
